/* tslint:disable */
/* eslint-disable */
/**
 * Twelve Data API client for Node.js
 *
 * NOTE: This code is auto generated, please do not edit it manually.
 */
import { mapValues } from "../runtime";
/**
 * Operating activities section
 * @export
 * @interface CashFlowStructOperatingActivities
 */
export interface CashFlowStructOperatingActivities {
  /**
   * Returns net income (NI). Calculated as sales minus cost of goods sold
   * @type {number}
   * @memberof CashFlowStructOperatingActivities
   */
  netIncome?: number;
  /**
   * Represents depreciation and amortization measure
   * @type {number}
   * @memberof CashFlowStructOperatingActivities
   */
  depreciation?: number;
  /**
   * Stands for taxes that are owed but are not due to be paid until a future date
   * @type {number}
   * @memberof CashFlowStructOperatingActivities
   */
  deferredTaxes?: number;
  /**
   * Refers to share-based compensation as the way of paying employees, executives, and directors of a company with equity in the business
   * @type {number}
   * @memberof CashFlowStructOperatingActivities
   */
  stockBasedCompensation?: number;
  /**
   * Represents other non-cash items
   * @type {number}
   * @memberof CashFlowStructOperatingActivities
   */
  otherNonCashItems?: number;
  /**
   * Represents the balance of money due to a firm for goods or services delivered or used but not yet paid for by customers
   * @type {number}
   * @memberof CashFlowStructOperatingActivities
   */
  accountsReceivable?: number;
  /**
   * Refers to an account within the general ledger that represents an obligation to pay off a short-term debt to creditors or suppliers
   * @type {number}
   * @memberof CashFlowStructOperatingActivities
   */
  accountsPayable?: number;
  /**
   * Represents cumulative changes in inventory, other current assets, other current liabilities, and other working capital
   * @type {number}
   * @memberof CashFlowStructOperatingActivities
   */
  otherAssetsLiabilities?: number;
  /**
   * Returns operating cash flow (OCF) measure representing a total amount of cash generated by company's normal business operations
   * @type {number}
   * @memberof CashFlowStructOperatingActivities
   */
  operatingCashFlow?: number;
}

/**
 * Check if a given object implements the CashFlowStructOperatingActivities interface.
 */
export function instanceOfCashFlowStructOperatingActivities(
  value: object,
): value is CashFlowStructOperatingActivities {
  return true;
}

export function CashFlowStructOperatingActivitiesFromJSON(
  json: any,
): CashFlowStructOperatingActivities {
  return CashFlowStructOperatingActivitiesFromJSONTyped(json, false);
}

export function CashFlowStructOperatingActivitiesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CashFlowStructOperatingActivities {
  if (json == null) {
    return json;
  }
  return {
    netIncome: json["net_income"] == null ? undefined : json["net_income"],
    depreciation:
      json["depreciation"] == null ? undefined : json["depreciation"],
    deferredTaxes:
      json["deferred_taxes"] == null ? undefined : json["deferred_taxes"],
    stockBasedCompensation:
      json["stock_based_compensation"] == null
        ? undefined
        : json["stock_based_compensation"],
    otherNonCashItems:
      json["other_non_cash_items"] == null
        ? undefined
        : json["other_non_cash_items"],
    accountsReceivable:
      json["accounts_receivable"] == null
        ? undefined
        : json["accounts_receivable"],
    accountsPayable:
      json["accounts_payable"] == null ? undefined : json["accounts_payable"],
    otherAssetsLiabilities:
      json["other_assets_liabilities"] == null
        ? undefined
        : json["other_assets_liabilities"],
    operatingCashFlow:
      json["operating_cash_flow"] == null
        ? undefined
        : json["operating_cash_flow"],
  };
}

export function CashFlowStructOperatingActivitiesToJSON(
  json: any,
): CashFlowStructOperatingActivities {
  return CashFlowStructOperatingActivitiesToJSONTyped(json, false);
}

export function CashFlowStructOperatingActivitiesToJSONTyped(
  value?: CashFlowStructOperatingActivities | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    net_income: value["netIncome"],
    depreciation: value["depreciation"],
    deferred_taxes: value["deferredTaxes"],
    stock_based_compensation: value["stockBasedCompensation"],
    other_non_cash_items: value["otherNonCashItems"],
    accounts_receivable: value["accountsReceivable"],
    accounts_payable: value["accountsPayable"],
    other_assets_liabilities: value["otherAssetsLiabilities"],
    operating_cash_flow: value["operatingCashFlow"],
  };
}
