/* tslint:disable */
/* eslint-disable */
/**
 * Twelve Data API client for Node.js
 *
 * NOTE: This code is auto generated, please do not edit it manually.
 */
import { mapValues } from "../runtime";
/**
 * A brief summary of a ETF
 * @export
 * @interface GetETFsWorldSummary200ResponseEtfSummary
 */
export interface GetETFsWorldSummary200ResponseEtfSummary {
  /**
   * All available fund types segmented by country
   * @type {string}
   * @memberof GetETFsWorldSummary200ResponseEtfSummary
   */
  symbol?: string;
  /**
   * Fund name
   * @type {string}
   * @memberof GetETFsWorldSummary200ResponseEtfSummary
   */
  name?: string;
  /**
   * Investment company that manages the fund
   * @type {string}
   * @memberof GetETFsWorldSummary200ResponseEtfSummary
   */
  fundFamily?: string;
  /**
   * Type of the fund
   * @type {string}
   * @memberof GetETFsWorldSummary200ResponseEtfSummary
   */
  fundType?: string;
  /**
   * Currency of fund price
   * @type {string}
   * @memberof GetETFsWorldSummary200ResponseEtfSummary
   */
  currency?: string;
  /**
   * The date from which the fund started operations and the returns are calculated
   * @type {string}
   * @memberof GetETFsWorldSummary200ResponseEtfSummary
   */
  shareClassInceptionDate?: string;
  /**
   * Percentage of profit of the fund since the first trading day of the current calendar year
   * @type {number}
   * @memberof GetETFsWorldSummary200ResponseEtfSummary
   */
  ytdReturn?: number;
  /**
   * Percentage of ETF assets steered toward a fund's operating expenses and fund management fees
   * @type {number}
   * @memberof GetETFsWorldSummary200ResponseEtfSummary
   */
  expenseRatioNet?: number;
  /**
   * Income returned to its investors through interest and dividends generated by the fund's investments
   * @type {number}
   * @memberof GetETFsWorldSummary200ResponseEtfSummary
   */
  _yield?: number;
  /**
   * Net Asset Value: fund value minus liabilities
   * @type {number}
   * @memberof GetETFsWorldSummary200ResponseEtfSummary
   */
  nav?: number;
  /**
   * Last price of the fund
   * @type {number}
   * @memberof GetETFsWorldSummary200ResponseEtfSummary
   */
  lastPrice?: number;
  /**
   * Percentage rate at which ETF replaces its holdings on investment every year
   * @type {number}
   * @memberof GetETFsWorldSummary200ResponseEtfSummary
   */
  turnoverRate?: number;
  /**
   * Total assets of a fund minus its total liabilities
   * @type {number}
   * @memberof GetETFsWorldSummary200ResponseEtfSummary
   */
  netAssets?: number;
  /**
   * Description of the fund
   * @type {string}
   * @memberof GetETFsWorldSummary200ResponseEtfSummary
   */
  overview?: string;
}

/**
 * Check if a given object implements the GetETFsWorldSummary200ResponseEtfSummary interface.
 */
export function instanceOfGetETFsWorldSummary200ResponseEtfSummary(
  value: object,
): value is GetETFsWorldSummary200ResponseEtfSummary {
  return true;
}

export function GetETFsWorldSummary200ResponseEtfSummaryFromJSON(
  json: any,
): GetETFsWorldSummary200ResponseEtfSummary {
  return GetETFsWorldSummary200ResponseEtfSummaryFromJSONTyped(json, false);
}

export function GetETFsWorldSummary200ResponseEtfSummaryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetETFsWorldSummary200ResponseEtfSummary {
  if (json == null) {
    return json;
  }
  return {
    symbol: json["symbol"] == null ? undefined : json["symbol"],
    name: json["name"] == null ? undefined : json["name"],
    fundFamily: json["fund_family"] == null ? undefined : json["fund_family"],
    fundType: json["fund_type"] == null ? undefined : json["fund_type"],
    currency: json["currency"] == null ? undefined : json["currency"],
    shareClassInceptionDate:
      json["share_class_inception_date"] == null
        ? undefined
        : json["share_class_inception_date"],
    ytdReturn: json["ytd_return"] == null ? undefined : json["ytd_return"],
    expenseRatioNet:
      json["expense_ratio_net"] == null ? undefined : json["expense_ratio_net"],
    _yield: json["yield"] == null ? undefined : json["yield"],
    nav: json["nav"] == null ? undefined : json["nav"],
    lastPrice: json["last_price"] == null ? undefined : json["last_price"],
    turnoverRate:
      json["turnover_rate"] == null ? undefined : json["turnover_rate"],
    netAssets: json["net_assets"] == null ? undefined : json["net_assets"],
    overview: json["overview"] == null ? undefined : json["overview"],
  };
}

export function GetETFsWorldSummary200ResponseEtfSummaryToJSON(
  json: any,
): GetETFsWorldSummary200ResponseEtfSummary {
  return GetETFsWorldSummary200ResponseEtfSummaryToJSONTyped(json, false);
}

export function GetETFsWorldSummary200ResponseEtfSummaryToJSONTyped(
  value?: GetETFsWorldSummary200ResponseEtfSummary | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    symbol: value["symbol"],
    name: value["name"],
    fund_family: value["fundFamily"],
    fund_type: value["fundType"],
    currency: value["currency"],
    share_class_inception_date: value["shareClassInceptionDate"],
    ytd_return: value["ytdReturn"],
    expense_ratio_net: value["expenseRatioNet"],
    yield: value["_yield"],
    nav: value["nav"],
    last_price: value["lastPrice"],
    turnover_rate: value["turnoverRate"],
    net_assets: value["netAssets"],
    overview: value["overview"],
  };
}
