/* tslint:disable */
/* eslint-disable */
/**
 * Twelve Data API client for Node.js
 *
 * NOTE: This code is auto generated, please do not edit it manually.
 */
import { mapValues } from "../runtime";
import type { GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInner } from "./GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInner";
import {
  GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInnerFromJSON,
  GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInnerFromJSONTyped,
  GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInnerToJSON,
  GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInnerToJSONTyped,
} from "./GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInner";

/**
 * A brief summary of a mutual fund
 * @export
 * @interface ResponseMutualFundWorldSummary
 */
export interface ResponseMutualFundWorldSummary {
  /**
   * All available fund types segmented by country
   * @type {string}
   * @memberof ResponseMutualFundWorldSummary
   */
  symbol?: string;
  /**
   * Fund name
   * @type {string}
   * @memberof ResponseMutualFundWorldSummary
   */
  name?: string;
  /**
   * Investment company that manages the fund
   * @type {string}
   * @memberof ResponseMutualFundWorldSummary
   */
  fundFamily?: string;
  /**
   * Type of the fund
   * @type {string}
   * @memberof ResponseMutualFundWorldSummary
   */
  fundType?: string;
  /**
   * Currency of fund price
   * @type {string}
   * @memberof ResponseMutualFundWorldSummary
   */
  currency?: string;
  /**
   * The date from which the fund started operations and the returns are calculated
   * @type {string}
   * @memberof ResponseMutualFundWorldSummary
   */
  shareClassInceptionDate?: string;
  /**
   * Percentage of profit of the fund since the first trading day of the current calendar year
   * @type {number}
   * @memberof ResponseMutualFundWorldSummary
   */
  ytdReturn?: number;
  /**
   * Percentage of mutual fund assets steered toward a fund's operating expenses and fund management fees
   * @type {number}
   * @memberof ResponseMutualFundWorldSummary
   */
  expenseRatioNet?: number;
  /**
   * Income returned to its investors through interest and dividends generated by the fund's investments
   * @type {number}
   * @memberof ResponseMutualFundWorldSummary
   */
  _yield?: number;
  /**
   * Net Asset Value: fund value minus liabilities
   * @type {number}
   * @memberof ResponseMutualFundWorldSummary
   */
  nav?: number;
  /**
   * Investment minimum
   * @type {number}
   * @memberof ResponseMutualFundWorldSummary
   */
  minInvestment?: number;
  /**
   * Percentage rate at which mutual fund replaces its holdings on investment every year
   * @type {number}
   * @memberof ResponseMutualFundWorldSummary
   */
  turnoverRate?: number;
  /**
   * Total assets of a fund minus its total liabilities
   * @type {number}
   * @memberof ResponseMutualFundWorldSummary
   */
  netAssets?: number;
  /**
   * Description of the fund
   * @type {string}
   * @memberof ResponseMutualFundWorldSummary
   */
  overview?: string;
  /**
   * Information about the fund’s managers
   * @type {Array<GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInner>}
   * @memberof ResponseMutualFundWorldSummary
   */
  people?: Array<GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInner>;
}

/**
 * Check if a given object implements the ResponseMutualFundWorldSummary interface.
 */
export function instanceOfResponseMutualFundWorldSummary(
  value: object,
): value is ResponseMutualFundWorldSummary {
  return true;
}

export function ResponseMutualFundWorldSummaryFromJSON(
  json: any,
): ResponseMutualFundWorldSummary {
  return ResponseMutualFundWorldSummaryFromJSONTyped(json, false);
}

export function ResponseMutualFundWorldSummaryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResponseMutualFundWorldSummary {
  if (json == null) {
    return json;
  }
  return {
    symbol: json["symbol"] == null ? undefined : json["symbol"],
    name: json["name"] == null ? undefined : json["name"],
    fundFamily: json["fund_family"] == null ? undefined : json["fund_family"],
    fundType: json["fund_type"] == null ? undefined : json["fund_type"],
    currency: json["currency"] == null ? undefined : json["currency"],
    shareClassInceptionDate:
      json["share_class_inception_date"] == null
        ? undefined
        : json["share_class_inception_date"],
    ytdReturn: json["ytd_return"] == null ? undefined : json["ytd_return"],
    expenseRatioNet:
      json["expense_ratio_net"] == null ? undefined : json["expense_ratio_net"],
    _yield: json["yield"] == null ? undefined : json["yield"],
    nav: json["nav"] == null ? undefined : json["nav"],
    minInvestment:
      json["min_investment"] == null ? undefined : json["min_investment"],
    turnoverRate:
      json["turnover_rate"] == null ? undefined : json["turnover_rate"],
    netAssets: json["net_assets"] == null ? undefined : json["net_assets"],
    overview: json["overview"] == null ? undefined : json["overview"],
    people:
      json["people"] == null
        ? undefined
        : (json["people"] as Array<any>).map(
            GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInnerFromJSON,
          ),
  };
}

export function ResponseMutualFundWorldSummaryToJSON(
  json: any,
): ResponseMutualFundWorldSummary {
  return ResponseMutualFundWorldSummaryToJSONTyped(json, false);
}

export function ResponseMutualFundWorldSummaryToJSONTyped(
  value?: ResponseMutualFundWorldSummary | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    symbol: value["symbol"],
    name: value["name"],
    fund_family: value["fundFamily"],
    fund_type: value["fundType"],
    currency: value["currency"],
    share_class_inception_date: value["shareClassInceptionDate"],
    ytd_return: value["ytdReturn"],
    expense_ratio_net: value["expenseRatioNet"],
    yield: value["_yield"],
    nav: value["nav"],
    min_investment: value["minInvestment"],
    turnover_rate: value["turnoverRate"],
    net_assets: value["netAssets"],
    overview: value["overview"],
    people:
      value["people"] == null
        ? undefined
        : (value["people"] as Array<any>).map(
            GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInnerToJSON,
          ),
  };
}
