/* tslint:disable */
/* eslint-disable */
/**
 * Twelve Data API client for Node.js
 *
 * NOTE: This code is auto generated, please do not edit it manually.
 */

/**
 * Operating activities section
 */
export interface CashFlowStructOperatingActivities {
  /**
   * Returns net income (NI). Calculated as sales minus cost of goods sold
   */
  net_income?: number;
  /**
   * Represents depreciation and amortization measure
   */
  depreciation?: number;
  /**
   * Stands for taxes that are owed but are not due to be paid until a future date
   */
  deferred_taxes?: number;
  /**
   * Refers to share-based compensation as the way of paying employees, executives, and directors of a company with equity in the business
   */
  stock_based_compensation?: number;
  /**
   * Represents other non-cash items
   */
  other_non_cash_items?: number;
  /**
   * Represents the balance of money due to a firm for goods or services delivered or used but not yet paid for by customers
   */
  accounts_receivable?: number;
  /**
   * Refers to an account within the general ledger that represents an obligation to pay off a short-term debt to creditors or suppliers
   */
  accounts_payable?: number;
  /**
   * Represents cumulative changes in inventory, other current assets, other current liabilities, and other working capital
   */
  other_assets_liabilities?: number;
  /**
   * Returns operating cash flow (OCF) measure representing a total amount of cash generated by company\'s normal business operations
   */
  operating_cash_flow?: number;
}
