/* tslint:disable */
/* eslint-disable */
/**
 * Twelve Data API client for Node.js
 *
 * NOTE: This code is auto generated, please do not edit it manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInner } from "./get-mutual-funds-world200-response-mutual-fund-summary-people-inner";

/**
 * A brief summary of a mutual fund
 */
export interface GetMutualFundsWorld200ResponseMutualFundSummary {
  /**
   * All available fund types segmented by country
   */
  symbol?: string;
  /**
   * Fund name
   */
  name?: string;
  /**
   * Investment company that manages the fund
   */
  fund_family?: string;
  /**
   * Type of the fund
   */
  fund_type?: string;
  /**
   * Currency of fund price
   */
  currency?: string;
  /**
   * The date from which the fund started operations and the returns are calculated
   */
  share_class_inception_date?: string;
  /**
   * Percentage of profit of the fund since the first trading day of the current calendar year
   */
  ytd_return?: number;
  /**
   * Percentage of mutual fund assets steered toward a fund\'s operating expenses and fund management fees
   */
  expense_ratio_net?: number;
  /**
   * Income returned to its investors through interest and dividends generated by the fund\'s investments
   */
  yield?: number;
  /**
   * Net Asset Value: fund value minus liabilities
   */
  nav?: number;
  /**
   * Investment minimum
   */
  min_investment?: number;
  /**
   * Percentage rate at which mutual fund replaces its holdings on investment every year
   */
  turnover_rate?: number;
  /**
   * Total assets of a fund minus its total liabilities
   */
  net_assets?: number;
  /**
   * Description of the fund
   */
  overview?: string;
  /**
   * Information about the fund’s managers
   */
  people?: Array<GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInner>;
}
