/* tslint:disable */
/* eslint-disable */
/**
 * Twelve Data API client for Node.js
 *
 * NOTE: This code is auto generated, please do not edit it manually.
 */

/**
 * A brief summary of a etf
 */
export interface GetETFsWorld200ResponseEtfSummary {
  /**
   * All available fund types segmented by country
   */
  symbol?: string;
  /**
   * Fund name
   */
  name?: string;
  /**
   * Investment company that manages the fund
   */
  fund_family?: string;
  /**
   * Type of the fund
   */
  fund_type?: string;
  /**
   * Currency of fund price
   */
  currency?: string;
  /**
   * The date from which the fund started operations and the returns are calculated
   */
  share_class_inception_date?: string;
  /**
   * Percentage of profit of the fund since the first trading day of the current calendar year
   */
  ytd_return?: number;
  /**
   * Percentage of ETF assets steered toward a fund\'s operating expenses and fund management fees
   */
  expense_ratio_net?: number;
  /**
   * Income returned to its investors through interest and dividends generated by the fund\'s investments
   */
  yield?: number;
  /**
   * Net Asset Value: fund value minus liabilities
   */
  nav?: number;
  /**
   * Last price of the fund
   */
  last_price?: number;
  /**
   * Percentage rate at which ETF replaces its holdings on investment every year
   */
  turnover_rate?: number;
  /**
   * Total assets of a fund minus its total liabilities
   */
  net_assets?: number;
  /**
   * Description of the fund
   */
  overview?: string;
}
